---
- name: "Deploy Docker"
  hosts: "{{ tower_env | default([]) }}"
  gather_facts: true
  become: true
  become_method: "ansible.builtin.sudo"

  tasks:

    - name: "Install Docker"
      when: inv_install_docker | default(false)
      block:
        - name: "Include labocbz.prepare_host"
          tags:
            - "labocbz.prepare_host"
          ansible.builtin.include_role:
            name: "labocbz.prepare_host"

        - name: "Include labocbz.install_docker"
          tags:
            - "labocbz.install_docker"
          vars:
            install_docker__portainer: "{{ inv_install_docker__portainer }}"
            install_docker__portainer_http_port: "{{ inv_install_docker__portainer_http_port }}"
            install_docker__portainer_https_port: "{{ inv_install_docker__portainer_https_port }}"
            install_docker__portainer_agent_port: "{{ inv_install_docker__portainer_agent_port }}"
            install_docker__portainer_container_name: "{{ inv_install_docker__portainer_container_name }}"
            install_docker__portainer_volume_name: "{{ inv_install_docker__portainer_volume_name }}"
            install_docker__portainer_ssl: "{{ inv_install_docker__portainer_ssl }}"
            install_docker__portainer_ssl_volume_name: "{{ inv_install_docker__portainer_ssl_volume_name }}"
            install_docker__portainer_ssl_key: "{{ inv_install_docker__portainer_ssl_cert }}"
            install_docker__watchtower: "{{ inv_install_docker__watchtower }}"
            install_docker__watchtower_poll_interval: "{{ inv_install_docker__watchtower_poll_interval }}"
            install_docker__watchtower_cleanup: "{{ inv_install_docker__watchtower_cleanup }}"
            install_docker__watchtower_include_restarting: "{{ inv_install_docker__watchtower_include_restarting }}"
            install_docker__watchtower_include_stopped: "{{ inv_install_docker__watchtower_include_stopped }}"
            install_docker__watchtower_no_restart: "{{ inv_install_docker__watchtower_no_restart }}"
            install_docker__portainer_address: "{{ inv_install_docker__portainer_address }}"
            install_docker__handle_clean: "{{ inv_install_docker__handle_clean }}"
            install_docker__clean_cron_file: "{{ inv_install_docker__clean_cron_file }}"
            install_docker__clean_weekday: "{{ inv_install_docker__clean_weekday }}"
            install_docker__clean_minute: "{{ inv_install_docker__clean_minute }}"
            install_docker__clean_hour: "{{ inv_install_docker__clean_hour }}"
            install_docker__insecure_registries: "{{ inv_install_docker__insecure_registries }}"
          ansible.builtin.include_role:
            name: "labocbz.install_docker"

    - name: "Install GitLab runner"
      when: inv_install_gitlab_runner | default(false)
      block:
        - name: "Include labocbz.install_gitlab_runner"
          tags:
            - "labocbz.install_gitlab_runner"
          vars:
            install_gitlab_runner__concurrent: "{{ inv_install_gitlab_runner__concurrent }}"
            install_gitlab_runner__session_timeout: "{{ inv_install_gitlab_runner__session_timeout }}"
            install_gitlab_runner__image: "{{ inv_install_gitlab_runner__image }}"
            install_gitlab_runner__name: "{{ inv_install_gitlab_runner__name }}"
            install_gitlab_runner__url: "{{ inv_install_gitlab_runner__url }}"
            install_gitlab_runner__token: "{{ inv_install_gitlab_runner__token }}"
            install_gitlab_runner__config_volume: "{{ inv_install_gitlab_runner__config_volume }}"
            install_gitlab_runner__docker_tls_verify: "{{ inv_install_gitlab_runner__docker_tls_verify }}"
            install_gitlab_runner__docker_image: "{{ inv_install_gitlab_runner__docker_image }}"
            install_gitlab_runner__pull_policy: "{{ inv_install_gitlab_runner__pull_policy }}"
            install_gitlab_runner__force_register: "{{ inv_install_gitlab_runner__force_register }}"
            install_gitlab_runner__docker_privileged: "{{ inv_install_gitlab_runner__docker_privileged }}"
          ansible.builtin.include_role:
            name: "labocbz.install_gitlab_runner"
